import { TimePersona, TimeRecipe, CreatorProfile } from "./types";

export const DEFAULT_PERSONAS: TimePersona[] = [
  {
    id: "coffee",
    name: "바리스타",
    subtitle: "추출 촉매제",
    tagline: "시간은 숫자가 아닌 추출의 과정이 됩니다.",
    theme: "warm-amber",
    icon: "Coffee",
    visualMetaphor: "coffee",
    language: {
      start: "추출 시작",
      pause: "추출 일시정지",
      resume: "추출 재개",
      lap: "다음 단계",
      stop: "추출 완료",
      elapsedLabel: "추출 시간",
      lapLabel: "현재 추출 단계",
    },
    feedbackStyle: "sensory",
  },
  {
    id: "cooking",
    name: "요리",
    subtitle: "열의 지휘자",
    tagline: "시간은 곧 풍미입니다. 열기를 음미하세요.",
    theme: "sunset-red",
    icon: "Flame",
    visualMetaphor: "fire",
    language: {
      start: "그릴 가열",
      pause: "열기 유지",
      resume: "가열 재개",
      lap: "단계 기록",
      stop: "플레이팅 및 서빙",
      elapsedLabel: "지글거리는 시간",
      lapLabel: "인터벌 휴식",
    },
    feedbackStyle: "performance",
  },
  {
    id: "baby",
    name: "육아",
    subtitle: "따뜻한 심장박동",
    tagline: "시간은 보살핌이 됩니다. 부드럽고 꾸준하게.",
    theme: "sand-gold",
    icon: "Baby",
    visualMetaphor: "hourglass",
    language: {
      start: "수유 시작",
      pause: "아기 달래기",
      resume: "보살핌 재개",
      lap: "트림 / 방향 전환",
      stop: "수면 루틴 시작",
      elapsedLabel: "돌봄의 흐름",
      lapLabel: "세션 단계",
    },
    feedbackStyle: "gentle",
  },
  {
    id: "workout",
    name: "코치",
    subtitle: "수행 능력 조각가",
    tagline: "시간은 에너지가 됩니다. 한계를 뛰어넘으세요.",
    theme: "neon-cyan",
    icon: "Dumbbell",
    visualMetaphor: "ripple",
    language: {
      start: "세트 1 시작",
      pause: "숨 고르기",
      resume: "트레이닝 재개",
      lap: "세트 완료",
      stop: "운동 완료",
      elapsedLabel: "에너지 소모",
      lapLabel: "활성 세트",
    },
    feedbackStyle: "performance",
  },
  {
    id: "study",
    name: "집중",
    subtitle: "인지적 보호막",
    tagline: "시간은 주의 집중입니다. 소음을 최소화하세요.",
    theme: "forest-green",
    icon: "Brain",
    visualMetaphor: "leaves",
    language: {
      start: "몰입 상태 진입",
      pause: "방해 감지",
      resume: "몰입 재개",
      lap: "깊은 생각",
      stop: "집중 종료",
      elapsedLabel: "집중 시간",
      lapLabel: "집중 구간",
    },
    feedbackStyle: "calm",
  },
  {
    id: "meditation",
    name: "명상",
    subtitle: "무한한 공간",
    tagline: "숫자는 사라집니다. 오직 호흡만이 존재합니다.",
    theme: "space-indigo",
    icon: "Heart",
    visualMetaphor: "moon",
    language: {
      start: "평온 들이마시기",
      pause: "숨 참기",
      resume: "호흡 재개",
      lap: "마음 고정",
      stop: "완전히 내쉬기",
      elapsedLabel: "마인드풀니스",
      lapLabel: "호흡 주기",
    },
    feedbackStyle: "calm",
  },
  {
    id: "scientist",
    name: "퀀텀",
    subtitle: "시간 관찰자",
    tagline: "절대적인 정확성. 밀리초 단위의 원격 측정.",
    theme: "cosmic-slate",
    icon: "Compass",
    visualMetaphor: "galaxy",
    language: {
      start: "관찰 시작",
      pause: "원격 측정 중단",
      resume: "원격 측정 재개",
      lap: "인터벌 기록",
      stop: "테스트 종료",
      elapsedLabel: "퀀텀 측정",
      lapLabel: "하위 원자 분할",
    },
    feedbackStyle: "precision",
  },
  {
    id: "minimalist",
    name: "미니멀",
    subtitle: "비어 있는 캔버스",
    tagline: "깔끔하고 우아한 캔버스. 순수한 ticking 소리뿐.",
    theme: "cosmic-slate",
    icon: "Clock",
    visualMetaphor: "ripple",
    language: {
      start: "시작",
      pause: "일시정지",
      resume: "재개",
      lap: "랩",
      stop: "정지",
      elapsedLabel: "ticking",
      lapLabel: "스플릿",
    },
    feedbackStyle: "precision",
  },
  {
    id: "standard",
    name: "일반",
    subtitle: "표준 크로노미터",
    tagline: "가장 기본적이고 직관적인 스톱워치. 물리적인 정밀함을 제공합니다.",
    theme: "space-indigo",
    icon: "Clock",
    visualMetaphor: "clock",
    language: {
      start: "측정 시작",
      pause: "측정 일시정지",
      resume: "측정 재개",
      lap: "랩 타임 기록",
      stop: "측정 완료",
      elapsedLabel: "기록 시간",
      lapLabel: "구간 랩",
    },
    feedbackStyle: "precision",
  },
];

export const DEFAULT_RECIPES: TimeRecipe[] = [
  {
    id: "hoffmann-v60",
    name: "제임스 호프만 V60",
    description: "정밀한 뜸 들이기와 유량 일관성에 중점을 둔 완벽한 1인용 푸어오버 레시피입니다.",
    icon: "Coffee",
    visualMetaphor: "coffee",
    theme: "warm-amber",
    milestones: [
      { time: 0, label: "뜸 들이기 단계", instruction: "물 50g을 붓습니다. 원두가 완전히 젖도록 가볍게 흔들어 줍니다." },
      { time: 45, label: "1차 푸어", instruction: "150g까지 나선형으로 일정하게 물을 붓습니다. 물줄기를 부드럽고 깨끗하게 유지하세요." },
      { time: 80, label: "2차 푸어", instruction: "필터 벽에 붙은 원두를 씻어내며 나선형으로 250g까지 물을 붓습니다." },
      { time: 140, label: "추출 완료", instruction: "드리퍼를 가볍게 한 번 회전시킨 후 물이 완전히 빠지도록 둡니다. 황금빛 추출이 완성됩니다." },
    ],
    isCommunity: false,
    creator: "HoffmannBrewing",
    creatorRole: "커피 챔피언 & 작가",
    forks: 341,
    likes: 1290,
    downloads: 4890,
    rating: 4.9,
  },
  {
    id: "perfect-steak",
    name: "완벽한 미디엄 스테이크",
    description: "고급 스테이크를 시어링하고, 버터를 끼얹고, 뒤집고, 휴지(레스팅)시키는 동기화된 요리 리튜얼입니다.",
    icon: "Flame",
    visualMetaphor: "fire",
    theme: "sunset-red",
    milestones: [
      { time: 0, label: "A면 시어링", instruction: "연기가 나는 뜨거운 팬에 스테이크를 올립니다. 움직이지 말고 두어 깊은 크러스트가 생기게 합니다." },
      { time: 60, label: "뒤집기 & 버터", instruction: "B면으로 뒤집습니다. 버터, 로즈마리, 으깬 마늘을 추가합니다. 녹은 버터를 계속 끼얹어 줍니다." },
      { time: 120, label: "테두리 시어링", instruction: "집게를 사용하여 스테이크를 지방 부위로 세워 여분의 지방을 녹여냅니다." },
      { time: 150, label: "불 끄기 & 레스팅", instruction: "팬에서 꺼내 따뜻한 도마로 옮깁니다. 근육 섬유가 이완되고 육즙이 퍼지도록 둡니다." },
    ],
    isCommunity: false,
    creator: "ChefGordon",
    creatorRole: "미쉐린 스타 요리사",
    forks: 182,
    likes: 830,
    downloads: 3100,
    rating: 4.8,
  },
  {
    id: "pomodoro-focus",
    name: "25분 딥 포커스",
    description: "높은 인지적 경계 설정 코칭과 산만함 억제 피드백으로 몰입 상태를 활성화합니다.",
    icon: "Brain",
    visualMetaphor: "leaves",
    theme: "forest-green",
    milestones: [
      { time: 0, label: "초기 단계", instruction: "심호흡을 세 번 합니다. 모든 브라우저 탭을 닫고, 휴대폰을 치운 뒤 집중하기로 다짐하세요." },
      { time: 600, label: "집중 중반", instruction: "잘하고 계십니다. 흩어지는 생각을 다시 다잡으세요. 몰입도 하나의 근육입니다." },
      { time: 1200, label: "깊은 궤도", instruction: "피크 인지 상태에 도달했습니다. 알림을 확인하고 싶은 사소한 충동을 무시하세요." },
      { time: 1500, label: "휴식 돌입", instruction: "의식이 완료되었습니다. 눈을 쉬어주고 몸을 스트레칭하세요. 이제 5분간 휴식이 시작됩니다." },
    ],
    isCommunity: false,
    creator: "FocusAcademy",
    creatorRole: "인지 수행 연구소",
    forks: 412,
    likes: 1490,
    downloads: 8700,
    rating: 4.9,
  },
  {
    id: "morning-zen",
    name: "프라나야마 호흡법",
    description: "조절된 폐활량 확장, 순환식 호흡 유지, 안정을 주는 톤을 통해 시간의 흐름을 늦춥니다.",
    icon: "Heart",
    visualMetaphor: "moon",
    theme: "space-indigo",
    milestones: [
      { time: 0, label: "들이마시기 (4초)", instruction: "코로 깊게 숨을 들이마시며, 아랫배를 먼저 채운 뒤 가슴을 채웁니다." },
      { time: 30, label: "참기 (4초)", instruction: "어깨와 얼굴의 긴장을 풀고 호흡을 멈춥니다. 완벽한 내면의 고요함을 경험하세요." },
      { time: 60, label: "내쉬기 (4초)", instruction: "부드럽고 따뜻한 한숨과 함께 입을 통해 호흡을 완전히 내보냅니다." },
      { time: 90, label: "비우고 참기 (4초)", instruction: "다음 들숨이 오기 전 조용하고 비어 있는 공간에서 대기합니다. 현재의 존재감 속에 머무르세요." },
    ],
    isCommunity: false,
    creator: "YogiGuru",
    creatorRole: "요가 호흡 마스터",
    forks: 98,
    likes: 520,
    downloads: 1200,
    rating: 4.7,
  },
  {
    id: "hiit-sprint",
    name: "HIIT 타바타 서지",
    description: "20초 최대 퍼포먼스와 10초 회복을 교대로 반복하는 빠른 템포의 시청각 코칭입니다.",
    icon: "Dumbbell",
    visualMetaphor: "ripple",
    theme: "neon-cyan",
    milestones: [
      { time: 0, label: "인터벌 1: 푸시", instruction: "최대 출력! 하이 니(High Knees), 케틀벨 스윙 또는 전력 질주. 100%의 힘을 쏟으세요!" },
      { time: 20, label: "회복 인터벌", instruction: "완전한 휴식. 무릎에 손을 얹고 깊고 천천히 숨을 내쉽니다. 심박수를 낮추세요." },
      { time: 30, label: "인터벌 2: 푸시", instruction: "다시 시작합니다! 어제의 한계를 넘어서세요. 힘은 현재의 노력에서 나옵니다!" },
      { time: 50, label: "인터벌 2: 회복", instruction: "깊은 회복. 배로 깊이 숨을 쉽니다. 혈류가 산소를 가득 전달하게 하세요." },
    ],
    isCommunity: false,
    creator: "FitCoachMark",
    creatorRole: "올림픽 피트니스 코치",
    forks: 145,
    likes: 620,
    downloads: 2400,
    rating: 4.6,
  },
  {
    id: "cup-ramen",
    name: "컵라면 3분",
    description: "뜨거운 물을 붓고 정확히 3분. 면이 가장 탱글할 때 신호음이 알려주는 국민 타이머입니다.",
    icon: "Flame",
    visualMetaphor: "fire",
    theme: "sunset-red",
    milestones: [
      { time: 0, label: "뜨거운 물 붓기", instruction: "끓는 물을 안쪽 선까지 붓고 뚜껑을 덮어 밀봉하세요. 이제 기다립니다." },
      { time: 90, label: "면 익히는 중", instruction: "면이 물을 머금기 시작합니다. 뚜껑을 열지 말고 그대로 두세요." },
      { time: 150, label: "마무리 준비", instruction: "곧 완성입니다. 젓가락과 국물 마실 준비를 하세요." },
      { time: 180, label: "완성!", instruction: "뚜껑을 열고 잘 저어 드세요. 후후 불며 가장 맛있는 순간입니다." },
    ],
    isCommunity: false,
    creator: "Timeverse",
    creatorRole: "일상 리튜얼",
    rating: 4.8,
  },
  {
    id: "soft-egg",
    name: "반숙 계란 6분",
    description: "끓는 물에 넣는 순간부터 6분. 노른자가 촉촉하게 흐르는 완벽한 반숙 타이밍을 잡아줍니다.",
    icon: "Flame",
    visualMetaphor: "fire",
    theme: "warm-amber",
    milestones: [
      { time: 0, label: "계란 투입", instruction: "끓는 물에 실온 계란을 조심히 넣으세요. 살짝 저어 노른자를 가운데로 모읍니다." },
      { time: 180, label: "익는 중", instruction: "흰자가 단단해지고 있습니다. 불은 중약불로 유지하세요." },
      { time: 360, label: "반숙 완성!", instruction: "바로 꺼내 찬물에 담그세요. 노른자가 촉촉한 완벽한 반숙입니다." },
    ],
    isCommunity: false,
    creator: "Timeverse",
    creatorRole: "일상 리튜얼",
    rating: 4.7,
  },
  {
    id: "tea-steep",
    name: "홍차 우리기 3분",
    description: "티백을 담그고 3분. 떫은맛이 올라오기 직전, 향이 가장 풍부한 순간에 건져내도록 안내합니다.",
    icon: "Coffee",
    visualMetaphor: "coffee",
    theme: "warm-amber",
    milestones: [
      { time: 0, label: "티백 담그기", instruction: "갓 끓인 물(약 95℃)에 티백을 넣고 뚜껑을 덮으세요." },
      { time: 120, label: "우러나는 중", instruction: "찻물이 진하게 우러납니다. 티백을 휘젓지 말고 그대로 두세요." },
      { time: 180, label: "건져내기!", instruction: "티백을 부드럽게 흔들어 건져내세요. 떫은맛이 올라오기 전 최적의 순간입니다." },
    ],
    isCommunity: false,
    creator: "Timeverse",
    creatorRole: "일상 리튜얼",
    rating: 4.6,
  },
];

export const CREATORS: CreatorProfile[] = [
  {
    id: "hoffmann",
    name: "제임스 호프만",
    role: "커피 챔피언 & 작가",
    avatar: "☕",
    bio: "전 세계 커피 애호가들을 위해 커피 추출을 대중화하고 있습니다. 완벽한 V60 푸어 테크닉의 창시자입니다.",
    followers: 12400,
    recipesCount: 8,
    featuredRecipeId: "hoffmann-v60",
  },
  {
    id: "chef-ramsay",
    name: "고든 램지",
    role: "미쉐린 스타 요리사",
    avatar: "🍳",
    bio: "타협 없는 요리 정밀함. 열, 수분, 그리고 휴지(레스팅)가 어떻게 완벽함을 만들어내는지 가르칩니다.",
    followers: 43200,
    recipesCount: 15,
    featuredRecipeId: "perfect-steak",
  },
  {
    id: "focus-academy",
    name: "앤드류 휴버먼 박사",
    role: "신경생물학 교수",
    avatar: "🧠",
    bio: "몰입 상태 활성화 메커니즘, 도파민 관리, 집중 고정을 유도하기 위한 감각적 프로토콜을 설계합니다.",
    followers: 89000,
    recipesCount: 12,
    featuredRecipeId: "pomodoro-focus",
  },
];

// Complete blueprint documentation text for presentation inside the application itself
export const VISION_BLUEPRINT = {
  vision: {
    title: "TIMEVERSE: 완전한 제품 비전",
    bullets: [
      "시간의 재정의: 메마른 소수점 계산에서 마인드풀한 감각적 관찰로 시간 측정 패러다임을 바꿉니다.",
      "모듈형 핵심 엔진: 감각적 인터페이스와 분리된 정밀 ticking 엔진을 통해 스톱워치가 수백 개의 맞춤형 'Time Persona'로 변신합니다.",
      "경험적 메타포화: 숫자를 반응형 비주얼(예: 커피의 상승하는 따뜻한 호박색 액체, 명상의 확장하는 달 위상)로 대체하여 심리적 상태를 현재 활동에 일치시킵니다.",
      "미학적 정밀함: 깊은 우주적 슬레이트 톤과 풍부한 강조 색상으로 제작된 UI, 유기적이고 촉각적인 반응형 마이크로 애니메이션을 구현합니다."
    ]
  },
  architecture: {
    title: "정보 아키텍처 (IA)",
    structure: [
      {
        section: "1. 핵심 포털 (대시보드)",
        items: ["활성 경험 스테이지 (중앙 메타포 및 대형 디지털 카운터)", "페르소나 선택 레일 (바리스타, 셰프, 코치, 몽크, 젠 간 빠른 전환)", "활성 레시피 마일스톤 패널 (다음 단계 카운트다운, 가이드 카드)", "집중 방해 감지 및 원격 측정 스위처"]
      },
      {
        section: "2. 탐색 & 마켓플레이스",
        items: ["주요 마스터 리튜얼 (제임스 호프만 V60, 완벽한 미디엄 스테이크)", "리튜얼 카테고리 (가스트로노미, 인지, 웰니스, 수행 능력, 돌봄)", "레시피 카드의 포크, 좋아요 및 다운로드 수", "동적 검색 및 필터링 허브"]
      },
      {
        section: "3. 크리에이션 스튜디오 (AI 엔진)",
        items: ["AI 프롬프트 플레이그라운드 (Gemini를 통해 맞춤형 레시피를 동적으로 생성)", "수동 마일스톤 스튜디오 (맞춤 시간, 단계 및 테마 정의)", "커뮤니티 마켓플레이스에 원클릭 게시"]
      },
      {
        section: "4. 개인 아카이브 (인사이트)",
        items: ["마인드풀 로그북 (맞춤 메모 및 주의 산만 횟수가 포함된 완료 타이밍 세션)", "AI 철학자 인사이트 (집중 습관, 리튜얼 품질, 습관 루프에 대한 맞춤형 철학적 성찰)", "감각적 통계 (완료된 단계, 산만도 지표, 지속 시간 분포)"]
      }
    ]
  },
  userFlow: {
    title: "프리미엄 사용자 흐름",
    steps: [
      "1. 플랫폼 입장: 차분한 우주적 은하 메타포를 담은 미니멀한 슬레이트 대시보드로 사용자를 맞이합니다.",
      "2. 페르소나 또는 레시피 선택: 기본 페르소나(예: 바리스타)를 탐색하거나 맞춤 레시피(예: V60 푸어오버)를 불러옵니다. 전체 색상 팔레트, 아이콘 세트, 비주얼 모델 및 타이밍 레이블이 동적으로 전환됩니다.",
      "3. 경험 시작: '추출 시작'을 클릭합니다. 일반적인 숫자는 보조 수단이 되며, 가열된 유리잔 속 따뜻한 호박색 커피가 차오르고 미세한 김 모락모락 애니메이션이 나타납니다.",
      "4. 실시간 마일스톤: 시간이 진행됨에 따라 마일스톤(예: 45초에 '150g까지 붓기')에서 맞춤 청각/시각 알림이 트리거됩니다.",
      "5. 완료 및 성찰: 세션을 중지합니다. 메모를 작성하거나 방해 요소를 기록할 수 있습니다. 세션 기록은 Gemini AI에 의해 서버 측에서 분석되어 시간 사용에 대한 시적이고 깊이 있는 성찰을 생성합니다."
    ]
  },
  componentSystem: {
    title: "모듈형 컴포넌트 시스템",
    components: [
      { name: "TimeverseCoreEngine", desc: "정밀한 틱, 밀리초 단위 분할, 랩 기록, 일시정지/재개 제어 및 레시피 마일스톤 트리거를 관리하는 기본 훅." },
      { name: "VisualMetaphorStage", desc: "Tailwind로 구현되어 솟아오르는 액체, 피어오르는 화염, 흘러내리는 모래, 확장하는 물결 등 맞춤형 애니메이션 캔버스를 렌더링하는 컨테이너." },
      { name: "MilestoneGuide", desc: "현재, 완료, 다가오는 마일스톤을 깔끔하게 빛나는 노드로 추적하는 수평 스텝 시스템." },
      { name: "InteractiveLogbook", desc: "세션 기록, 완료된 레시피, 사용자 로그 및 집중 방해 지표를 보여주는 세련된 장부." },
      { name: "RecipeCreationStudio", desc: "서버의 Gemini-3.5-flash 엔드포인트로 요청을 전송하여 단 몇 초 만에 맞춤형 타이밍 워크플로우를 생성하는 고성능 프롬프트 포털." }
    ]
  },
  innovativeFeatures: [
    "1. 감각적 메타포 (숫자 타이머를 액체, 불꽃, 모래시계, 물결 등 실시간 캔버스 시뮬레이션으로 대체).",
    "2. AI 맞춤 레시피 생성기 (예: '카모마일 차 우리며 명상하기' 프롬프트를 입력하면 실시간으로 레시피를 빌드).",
    "3. AI 시간 철학자 (단순 수학적 통계를 너머 시간 소모 패턴과 마음가짐에 대한 에세이를 작성하는 성찰 가이드).",
    "4. 집중 방해 쉴드 (세션 중 '방해 요인 감지됨'을 누르면 인지 분석용 기록으로 로그에 남김).",
    "5. 모유 수유 측면 메모리 (부모 페르소나 사용 시 좌/우측 수유 중인 가슴 방향 기록).",
    "6. 바리스타 추출 곡선 오버레이 (시간에 따른 부은 물의 양과 타겟 추출 일치율 분석).",
    "7. 시즐 웨이브폼 (요리 중 마일스톤 도달 시 고기가 익어가는 소리와 반응형 화염 비주얼 애니메이션).",
    "8. 촉각 햅틱 펄서 (시각 차단 상태에서도 들숨/날숨 페이스를 맞출 수 있도록 화면이 부드럽게 고동하는 안개 연출).",
    "9. 퀀텀 밀리초 텔레메트리 (과학자 관찰자 모드에서 고정밀 스플릿 데이터를 실시간 SVG 플롯 차트로 가시화).",
    "10. 깃허브 스타일 마켓플레이스 (다른 사람이 설계한 타이밍 레시피를 포크하고, 라이크 및 복제 가능).",
    "11. 반응형 인터벌 휴식 주기 (이전 활성 운동 시간의 밀도를 계산하여 자동으로 보정된 휴식 시간 산출).",
    "12. 해빗 스트릭 플레임 (꾸준히 루틴을 달성한 일수에 비례하여 메인 대시보드의 은빛 불꽃이 다채롭게 진화).",
    "13. 리튜얼 사운드 제너레이터 (빗소리, 화덕 타닥이는 소리, 백색 소음을 페르소나 테마에 어우러지게 생성).",
    "14. 마음챙김 정지 질문 (타이머를 멈추었을 때 '정말로 필요한 멈춤인가요, 아니면 자극을 쫓는 방해인가요?' 제기).",
    "15. 극한의 미니멀 모드 (모든 인터페이스를 숨기고 하나의 서서히 움직이는 점만 남겨 호흡을 보조).",
    "16. 크로노 저널링 패드 (시간이 흐르는 동안 머릿속 의식의 흐름을 날것 그대로 남길 수 있는 즉각적 메모장).",
    "17. 실시간 화력 온도계 (셰프 페르소나 작동 시 팬 온도 상승과 수분 건조율을 그라데이션으로 가시화).",
    "18. 크리에이터 로열티 포인트 (배포한 가이드 레시피가 다른 사용자들에게 포크되고 사용될 때마다 리워드 부여).",
    "19. 신생아 케어 케스케이드 (아기 페르소나의 모유/트림/수면 상태 전환에 따른 원클릭 토글 기록 시스템).",
    "20. 앵커 메모 핀 (각 마일스톤 단계 도달 즉시 관찰한 아이디어를 타임스탬프와 매핑하여 앵커로 고정).",
    "21. 인지적 시간 왜곡 (훈련을 위해 인위적으로 시간을 10% 느리게 또는 빠르게 흘려보내는 인지 시뮬레이터).",
    "22. 화음 스플릿 피드백 (랩 기록 시마다 도레미파솔 솔레시도 감각적 화음이 한 옥타브씩 상승 전개).",
    "23. 라이브 동시 싱크 타이머 (전 세계 사용자들이 동일한 V60 레시피 혹은 요가 세션을 실시간으로 병렬 수행).",
    "24. 딥 포커스 잠금 (전체 화면 전환 후 세션을 이탈하거나 키보드를 조작해 다른 앱으로 이탈하는 것을 차단).",
    "25. 추출 프로파일 어드바이저 (커피 세션 종료 후 구간별 푸어 타임 차이를 인지해 분쇄도 조절 제안).",
    "26. 플루이디티 흐름 계수 (세션 중 일시정지 횟수와 집중 방해를 수치화해 정서적 일치성 점수 부여).",
    "27. 선셋 & 던 타임싱크 (로컬 시간에 반응해 새벽에는 안개 낀 블루톤, 저녁에는 은은한 노을 앰버 테마로 자동 변환).",
    "28. 음성 가이드 메트로놈 (바리스타의 푸어 지시나 명상의 깊은 이완 호흡을 잔잔한 사운드로 보조).",
    "29. 공유 스토리 피드 (단순 숫자 캡처가 아닌 당일의 성찰 카드와 완벽한 메타포 스케치를 실시간 전송).",
    "30. 크로노 쉴드 허드 (복잡한 대시보드를 차단하고 오직 하나의 다음 마일스톤 텍스트에만 시선을 유도)."
  ],
  differentiation: {
    whyLoved: "인간은 시간을 싫어하는 것이 아닙니다. 조급함과 압박감을 조장하는 차갑고 딱딱한 기계식 디지털 시계를 싫어할 뿐입니다. TIMEVERSE는 흘러가는 매 순간을 예술적인 하나의 리튜얼로 바꾸어, Routine 커피 브루잉, 요리, 육아, 공부가 늘 고무적이고 보람찬 여정으로 변모하도록 돕습니다.",
    moats: "1. 무한한 시각적/청각적 메타포를 바인딩할 수 있는 완벽한 비동기 스톱워치 코어. 2. 전 세계 전문가들이 공유하고 확장해 나가는 레시피 생태계. 3. 숫자를 인문학적, 성찰적 시선으로 풀어내는 고성능 AI 철학자 에세이 서비스.",
    newCategory: "이것은 유틸리티 도구를 넘어선 '시간 경험 플랫폼(Time Experience Platform)'입니다. 시계 앱이 제공하지 못하던 마인드풀니스, 몰입 습관, 요리와 육아의 실질적인 유저 친화적 정밀 케어를 고유한 심미성 안에서 달성합니다."
  }
};
